/******************************************************************************
*  Generated by PSoC Designer 5.0.1127.0
******************************************************************************/
#include <m8c.h>
// LED_1 address and mask defines
#pragma	ioport	LED_1_Data_ADDR:	0x4
BYTE			LED_1_Data_ADDR;
#pragma	ioport	LED_1_DriveMode_0_ADDR:	0x104
BYTE			LED_1_DriveMode_0_ADDR;
#pragma	ioport	LED_1_DriveMode_1_ADDR:	0x105
BYTE			LED_1_DriveMode_1_ADDR;
#pragma	ioport	LED_1_DriveMode_2_ADDR:	0x7
BYTE			LED_1_DriveMode_2_ADDR;
#pragma	ioport	LED_1_GlobalSelect_ADDR:	0x6
BYTE			LED_1_GlobalSelect_ADDR;
#pragma	ioport	LED_1_IntCtrl_0_ADDR:	0x106
BYTE			LED_1_IntCtrl_0_ADDR;
#pragma	ioport	LED_1_IntCtrl_1_ADDR:	0x107
BYTE			LED_1_IntCtrl_1_ADDR;
#pragma	ioport	LED_1_IntEn_ADDR:	0x5
BYTE			LED_1_IntEn_ADDR;
#define LED_1_MASK 0x4
#pragma	ioport	LED_1_MUXBusCtrl_ADDR:	0x1d9
BYTE			LED_1_MUXBusCtrl_ADDR;
